version: '3.8'


services:
  postgres:
    image: postgres
    container_name: postgres_ecommerce
    restart: always
    env_file:
      - config.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_ecommerce
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
